config/crd/kustomization.yaml, config/default/cainjection_conversion_webhook.yaml, config/default/inferenceservice_conversion_webhook.yaml, config/default/kustomization.yaml, config/default/network-policies.yaml, config/default/webhookcainjection_patch.yaml, pkg/apis/serving/v1beta1/predictor_model.go, pkg/apis/serving/v1beta1/predictor_model_test.go, pkg/controller/v1beta1/inferenceservice/utils/utils.go, pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
Related to opendatahub-io/odh-manifests#848
=> OpenShift patches to Kustomize manifests

.github/workflows/auto-add-issues-to-project.yaml
Automate addition of new issues into overall ODH boards and ML Serving board
Fixes #
- Logs
**Checklist**:
```release-note
```
=> automate addition of new isues into ODH board

OWNERS
Fixes #
- Logs
**Checklist**:
```release-note
```
=> add spoltin in the OWNERS file

config/overlays/odh/inferenceservice-config-patch.yaml, config/overlays/odh/kustomization.yaml, config/overlays/odh/params.env, config/overlays/odh/params.yaml, test/scripts/openshift-ci/deploy.serverless.sh
Same as #107, but for `master` branch.
Testing instructions are the same as in#107, but use `uri: 'https://github.com/israel-hdez/kserve/tarball/manifest-opv2-master` in `devFlags`.
=> [master] Preparation for odh-opeartor v2

config/default/kustomization.yaml
Cherrypick #120 to release branch
=> remove webhook from inferenceservice crd

config/overlays/odh/kustomization.yaml, config/overlays/odh/set-resources-manager-patch.yaml
Cherry-pick : https://github.com/opendatahub-io/kserve/pull/125
=> [Cherry-Pick] increase kserve controller limit resources(cpu/memory)

go.mod, go.sum, pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/webhook/admission/pod/storage_initializer_injector_test.go
chore: Fix Stack-based Buffer Overflow on protobuf on protobuf
- https://security.snyk.io/vuln/SNYK-GOLANG-GOOGLEGOLANGORGPROTOBUFENCODINGPROTOJSON-6137908
Fixes #
- Logs
1. Please confirm that if this PR changes any image versions, then that's the sole …
=> Fix Stack-based Buffer Overflow on protobuf

go.mod
chore: Fixes the following vulnerabilities in the go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp dependency:
- [CVE-2022-21698](https://www.cve.org/CVERecord?id=CVE-2022-21698) / [CVE-2023-45142](https://www.cve.org/CVERecord?id=CVE-2023-45142): Allocation of Resources Without Limits or Throttling
Fixes #
Please also list any relevant details …
=> Fixes vulnerabilities on the otelhttp dependency

config/overlays/odh/params.env
This PR updates the image tags for ODH release. Our current release points to latest tag which will change in the future. v0.11.1.1 is a static image tag that won't be updated.
Fixes #
- Logs
1. Please confirm that if this PR changes any image versions, then …
=> Update quay images to correct tag for odh release

config/overlays/odh/params.env
Version v0.11.1.2 will be the same as v0.11.1.1
=> Update references to images

python/kserve/kserve/storage/storage.py
Cherry-Pick : https://github.com/kserve/kserve/pull/3463
=> [Cherry-Pick] change certificate field for s3 storageSecret in python

config/overlays/odh/inferenceservice-config-patch.yaml
Fixes # https://issues.redhat.com/browse/RHOAIENG-3825
- verified change using `kustomize` 
```release-note
NONE
```
=> set disableIngressCreation to true in odh overlay

.gitignore
This solve merge conflict for syncing between rhoai master and rhoai release branch
=> add .tekton to gitignore to avoid conflict due to Konflux

.gitignore
cherry pick: https://github.com/opendatahub-io/kserve/pull/254
=> [Cherry Pick] add .tekton to gitignore to avoid conflict due to Konflux

config/overlays/odh/inferenceservice-config-patch.yaml
Fixing a missing comma from #251
=> fix syntax error in inferenceservice-config patch

config/overlays/odh/params.env
Fixes #
- Logs
**Checklist**:
```release-note
```
=> Prepare for ODH release and update params.env to 0.11.1.3

python/aiffairness/poetry.lock, python/alibiexplainer/poetry.lock, python/alibiexplainer/pyproject.toml, python/artexplainer/poetry.lock, python/custom_model/poetry.lock, python/custom_model/pyproject.toml, python/custom_transformer/poetry.lock, python/custom_transformer/pyproject.toml, python/kserve/poetry.lock, python/kserve/pyproject.toml, python/lgbserver/poetry.lock, python/paddleserver/poetry.lock, python/pmmlserver/poetry.lock, python/sklearnserver/poetry.lock, python/test_resources/graph/error_404_isvc/poetry.lock, python/test_resources/graph/success_200_isvc/poetry.lock, python/xgbserver/poetry.lock
chore: Fixes [CVE-2024-28219](https://www.cve.org/CVERecord?id=CVE-2024-28219)
Fixes #
- Logs
**Checklist**:
```release-note
```
=> [RHOAIENG-5335] [custom_model|trasformer] pillow - Buffer Overflow

test/scripts/openshift-ci/deploy.ossm.sh
Fixes #
- Logs
**Checklist**:
```release-note
```
=> remove unnecessary operators for e2e

test/scripts/openshift-ci/deploy.ossm.sh
Fixes #
- Logs
**Checklist**:
```release-note
```
=> remove unnecessary operators

Dockerfile, agent.Dockerfile, python/storage-initializer.Dockerfile, router.Dockerfile
=> replace upstream Dockerfiles with ubi dockerfiles.

config/overlays/odh/inferenceservice-config-patch.yaml
Fixes https://issues.redhat.com/browse/RHOAIENG-8287 
- Logs
**Checklist**:
```release-note
```
- …
=> enable DirectPvcVolumeMount

pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
cherry pick: https://github.com/opendatahub-io/kserve/pull/369
=> cherry-pick(#369) and fix conflict

config/overlays/odh/inferenceservice-config-patch.yaml
Cherry-pick https://github.com/opendatahub-io/kserve/pull/372
=> [Cherry-pick] update local gateway information

config/overlays/odh/inferenceservice-config-patch.yaml
This is for https://github.com/opendatahub-io/kserve/issues/371. For internal communication using a new gateway kserve-local-gateway, we need to update this change.
Fixes #
- Logs
1. Please confirm that if this PR changes any image versions, then that's the …
=> update local gateway information

config/overlays/odh/params.env
openshift ci will set different tag name so params.env need to use it.
Fixes # https://issues.redhat.com/browse/RHOAIENG-9790
- Logs
**Checklist**: …
=> Update Image tag that was being used by openshift ci

pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Fixes #
Cherry pick : https://github.com/opendatahub-io/kserve/pull/386
- Logs
**Checklist**:
```release-note
```
**Re-running failed …
=> [Cherry Pick] Change protocol 0.12.1

.github/workflows/agent-docker-publish.yml, .github/workflows/kserve-controller-docker-publish.yml, .github/workflows/qpext-docker-publish.yml, .github/workflows/router-docker-publish.yml
=> [release-v0.12.1] Removed arm/v7 to make the jobs working again for now

config/overlays/odh/inferenceservice-config-patch.yaml
Fixes #
- Logs
**Checklist**:
```release-note
```
- …
=> [RHOAIENG-12577] - enable modelCar by default

config/overlays/odh/inferenceservice-config-patch.yaml
=> [RHOAIENG-12577] - enable modelCar by default (#407)

config/overlays/odh/inferenceservice-config-patch.yaml
Fixes #
- Logs
**Checklist**:
```release-note
```
- …
=> Fix missing comma in inferenceservice-config-patch.yaml

python/storage-initializer.Dockerfile
Added commit from the main branch that needs to land in release.
chore:	Fix error: No available modular metadata for modular package
Fixes #
- Logs …
=> Sync with main

config/overlays/odh/set-resources-manager-patch.yaml
Reverts https://github.com/opendatahub-io/kserve/pull/261 which was a temporary fix until https://github.com/kserve/kserve/pull/3469 landed
- Logs
**Checklist**:
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. …
=> Revert 'Increase memory limit of kserve-controller pod'

.github/workflows/e2e-test.yml, config/crd/external/datasciencecluster.opendatahub.io_datascienceclusters.yaml, config/crd/external/dscinitialization.opendatahub.io_dscinitializations.yaml, config/crd/external/kustomization.yaml, config/default/kustomization.yaml, config/overlays/odh/set-resources-manager-patch.yaml, config/overlays/test/configmap/inferenceservice-openshift-ci-serverless.yaml, config/overlays/test/dsc.yaml, config/overlays/test/dsci.yaml, config/overlays/test/kustomization.yaml, test/e2e/common/utils.py, test/e2e/custom/test_custom_model_grpc.py, test/e2e/custom/test_ray.py, test/e2e/explainer/test_art_explainer.py, test/e2e/predictor/test_autoscaling.py, test/e2e/predictor/test_grpc.py, test/e2e/predictor/test_lightgbm.py, test/e2e/predictor/test_pmml.py, test/e2e/predictor/test_raw_deployment.py, test/e2e/predictor/test_response_headers.py, test/e2e/predictor/test_torchserve.py, test/e2e/predictor/test_xgboost.py, test/scripts/gh-actions/check-poetry-lockfile.sh, test/scripts/openshift-ci/run-e2e-tests.sh
- [Reduce E2Es dependency on CI environment (2) (](https://github.com/opendatahub-io/kserve/commit/37be2411b462687026686abac8d7bdb7c79c9cd2)https://github.com/kserve/kserve/pull/4008[)](https://github.com/opendatahub-io/kserve/commit/37be2411b462687026686abac8d7bdb7c79c9cd2)
- [Revert 'Increase memory limit of kserve-controller pod'](https://github.com/opendatahub-io/kserve/commit/5f1ff0498b6a101c50ba6b6201bd45b5cba0642a)
- [Fix issues after 0.14.0 sync (](https://github.com/opendatahub-io/kserve/commit/9f46725f5c2802959d6bfd7a986acef8c17aede2)https://github.com/opendatahub-io/kserve/pull/424[)](https://github.com/opendatahub-io/kserve/commit/9f46725f5c2802959d6bfd7a986acef8c17aede2)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
=> [Cherry-pick] To fix e2e test, cherry pick commits

config/overlays/odh/inferenceservice-config-patch.yaml
[RHOAIENG-15409](https://issues.redhat.com/browse/RHOAIENG-15409)
It missed `knativeLocalGatewayService` configuration so VirtualService set kserve-local-gateway as a default destination.
Fixes #
Sample isvc is not working.
- Logs
1. Please confirm that if …
=> [RHOAIENG-15409] add knativeLocalGatewayService to fix VS issue

config/overlays/odh/inferenceservice-config-patch.yaml
cherry-pick : https://github.com/opendatahub-io/kserve/pull/431
Fixes #
- Logs
**Checklist**:
```release-note
```
**Re-running failed …
=> [Cherry-Pick]  add knativeLocalGatewayService to fix VS issue 

pkg/constants/constants.go
chore:	Adds the `security.opendatahub.io/enable-auth` label to the ServiceAnnotationDisallowedList
to prevents the model to be rolled out in case the auth is disabled / enabled
Cherry-picks: https://github.com/opendatahub-io/kserve/pull/441
Fixes #
- Logs
1. …
=> [Cherry-Pick][RHOAIENG-11034] - Disabling Authorino Token Authorization forces a Model Pod to rollout

test/scripts/openshift-ci/kustomization.yaml, test/scripts/openshift-ci/run-e2e-tests.sh
Cherry picked commits:
-  https://github.com/opendatahub-io/kserve/commit/8074cae29b154e90dda137415ef07111a2ce69e5
- https://github.com/opendatahub-io/kserve/commit/ca82f169d5fb52d78a7920a491f23ebe5d4dbbb2
=> Synced the master branch to the release branch for ODH release v2.22

config/overlays/odh/params.env
Updated the release tag in the params.env file to use the v0.14 tag
=> Updated the release tag in the params.env file

docs/odh/oci-model-storage.md
Add GenAI example for using OCI images for model storage
Fixes https://issues.redhat.com/browse/RHOAIENG-16310
**Checklist**:
- [N/A] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
=> Add GenAI example for using OCI images for model storage

config/component_metadata.yaml
Closes: https://issues.redhat.com/browse/RHOAIENG-18612
Adding the release metadata that will be displayed in Dashboard
Fixes #
- Logs
**Checklist**: …
=> Add release metadata for kserve

config/crd/full/serving.kserve.io_inferencegraphs.yaml, config/crd/full/serving.kserve.io_inferenceservices.yaml, pkg/apis/serving/v1alpha1/inference_graph.go, pkg/apis/serving/v1beta1/inference_service_status.go, pkg/apis/serving/v1beta1/inference_service_validation.go, pkg/apis/serving/v1beta1/inference_service_validation_test.go, pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1beta1/inferenceservice/controller.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/utils/utils.go, pkg/controller/v1beta1/inferenceservice/utils/utils_test.go, pkg/openapi/openapi_generated.go, pkg/openapi/swagger.json, python/kserve/docs/V1alpha1InferenceGraphStatus.md, python/kserve/kserve/models/v1alpha1_inference_graph_status.py, test/crds/serving.kserve.io_inferenceservices.yaml
=> add DeploymentMode to InferenceService and InferenceGraph status

Dockerfile
=> Revert "Update Dockerfile (#489)"

config/component_metadata.yaml
Closes: https://issues.redhat.com/browse/RHOAIENG-18612
Adding the release metadata that will be displayed in Dashboard
Cherry pick of https://github.com/opendatahub-io/kserve/pull/478
Fixes #
- Logs
1. Please confirm that if this PR changes any image …
=> [Cherry-pick] from master to release: Add release metadata for kserve

config/runtimes/kserve-tensorflow-serving.yaml, test/scripts/openshift-ci/run-e2e-tests.sh, test/scripts/openshift-ci/setup-e2e-tests.sh
Fixes #
- Logs
**Checklist**:
```release-note
```
- …
=> enhance e2e test stability

test/scripts/openshift-ci/setup-e2e-tests.sh
Fixes #
- Logs
**Checklist**:
```release-note
```
- …
=> add networkpolicy for kserve namespace

config/runtimes/kserve-torchserve.yaml, config/runtimes/kserve-tritonserver.yaml, test/e2e/predictor/test_autoscaling.py
Fixes #
- Logs
**Checklist**:
```release-note
```
- …
=> [E2E Fix] Remove runAsUser from runtimes for e2e test and cherrypick of upstream 4276

config/runtimes/kserve-torchserve.yaml, config/runtimes/kserve-tritonserver.yaml, test/e2e/predictor/test_autoscaling.py, test/scripts/openshift-ci/setup-e2e-tests.sh
cherrypicks:
- https://github.com/opendatahub-io/kserve/pull/512
-  https://github.com/opendatahub-io/kserve/pull/513
Fixes #
- Logs
**Checklist**: …
=> [Cherry-Pick]regarding e2e fixes for predictor/path_based_routing

python/storage-initializer.Dockerfile
chore:	Update storage-initializer python version to 3.11+
Fixes #
- Logs
**Checklist**:
```release-note
``` …
=> [RHOAIENG-19883] - Update python to 3.11 on storate-initializer component

config/overlays/odh/inferenceservice-config-patch.yaml
This removes comments from inferenceservice-config configmap manifests that cause parsing issue.
Fixes #[RHOAIENG-21204](https://issues.redhat.com//browse/RHOAIENG-21204)
* Deploy kserve with the changes
* create a sample isvc
it should not show any errors.
- Logs
**Special notes for your …
=> Remove comments from inferenceservice-config configmap manifests

config/configmap/inferenceservice.yaml, config/overlays/odh/inferenceservice-config-patch.yaml, hack/violation_exceptions.list, pkg/apis/serving/v1beta1/component.go, pkg/apis/serving/v1beta1/configmap.go, pkg/apis/serving/v1beta1/configmap_test.go, pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/components/explainer.go, pkg/controller/v1beta1/inferenceservice/components/predictor.go, pkg/controller/v1beta1/inferenceservice/components/transformer.go, pkg/controller/v1beta1/inferenceservice/controller.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go, pkg/controller/v1beta1/inferenceservice/utils/utils.go, pkg/openapi/openapi_generated.go, pkg/openapi/swagger.json, python/kserve/docs/V1beta1InferenceServicesConfig.md, python/kserve/kserve/models/v1beta1_inference_services_config.py
Cherrypick
- https://github.com/opendatahub-io/kserve/commit/3c57909a87888479fdc8e927fbfa4588dc754664
- [PR 509](https://github.com/opendatahub-io/kserve/pull/509)
- [PR 510](https://github.com/opendatahub-io/kserve/pull/518)
Fixes #
- Logs
1. Please confirm …
=> [Cherrypick] Use annotation instead of label to enable auth for RawDeployment

pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/utils/utils.go, pkg/utils/utils_test.go
chore:  Fixes the reconcile loop to effectivelly update the EnvVars and replicas count.
Also address this issue: https://issues.redhat.com/browse/RHOAIENG-20634
Fixes #
- Logs
1. Please confirm that if this PR changes any image versions, then that's the sole …
=> [RHOAIENG-20548] - Env variable removed from ISVC are not removed from predictor pod

pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/utils/utils.go, pkg/utils/utils_test.go
chore:  Fixes the reconcile loop to effectivelly update the EnvVars and replicas count.
Also address this issue: https://issues.redhat.com/browse/RHOAIENG-20634
Cherry-picks: https://github.com/opendatahub-io/kserve/pull/516
---------
Fixes #
- Logs
1. …
=> [RHOAIENG-20548] - Env variable removed from ISVC are not removed from predictor pod (#516)

config/overlays/odh/inferenceservice-config-patch.yaml
Updated the domain template the automatically use example.com so users don't have to manually change it.
Fixes #
- Logs
**Checklist**: …
=> [RHOAIENG-9759] Update domain template value

pkg/apis/serving/v1beta1/configmap.go, pkg/apis/serving/v1beta1/configmap_test.go
Cherry-pick of #523 to `master`.
=> Use Headless Services by default 

config/rbac/role.yaml, pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/openshift_route_reconciler.go
Cherry-pick of #521
Related to https://issues.redhat.com/browse/RHOAIENG-20324
=> Ability to configure Raw InferenceGraphs as private

charts/kserve-resources/templates/clusterrole.yaml, cmd/router/main.go, config/rbac/role.yaml, pkg/constants/constants.go, pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/raw_ig.go, pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
Cherry-pick of #499 
Related to https://issues.redhat.com/browse/RHOAIENG-17832
=> Implement authorization for Raw InferenceGraphs

pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/openshift_route_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler_test.go
=> Fix oauth-proxy should not be injected to InferenceGraph [master]

config/overlays/odh/params.env
Fixes # https://issues.redhat.com/browse/RHOAIENG-23055 
- Logs
**Checklist**:
```release-note
```
- …
=> change oauth proxy image to be compatible with multi arch

cmd/router/main.go, pkg/controller/v1alpha1/inferencegraph/raw_ig.go, pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
=> add flag to control tls behavior for kserve router

pkg/webhook/admission/pod/agent_injector.go, pkg/webhook/admission/pod/agent_injector_test.go
Cherry-picks  https://github.com/opendatahub-io/kserve/commit/778089a6e17690dd970ccb7bc7885105d1783a63
=> [Cherry-pick][RHOAIENG-7607]Enhance InjectAgent to Handle Only HTTPGet, TCP Readiness Probes (#4012)

dev_tools/README.md, dev_tools/devspace.yaml, dev_tools/devspace_start.sh, dev_tools/kserve-devspace-debug.Containerfile, dev_tools/kserve-devspace-dev.Containerfile, test/scripts/openshift-ci/teardown-e2e-setup.sh
- Add devspace configurations similar to odh-model-controller for kserve, has usage documentation as well. 
- add teardown script for e2e tests (useful for local)
=> Add devtools and e2e teardown script 

pkg/controller/v1alpha1/inferencegraph/controller.go
=> Fix kserve-controller creating two InferenceGraph pods

config/overlays/odh/inferenceservice-config-patch.yaml, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
* disable autoMountServiceAccountToken globally and only enable when raw auth is requested
* pr feedback
---------
Fixes #
- Logs
**Checklist**: …
=> disable autoMountServiceAccountToken: true globally  (#553)

pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
Fixes #
- Logs
**Checklist**:
```release-note
```
- …
=> [RHOAIENG-19717] Old pull secret persists when updating isvcs (#522)

config/overlays/test/configmap/inferenceservice-openshift-ci-raw.yaml
Fixes https://issues.redhat.com/browse/RHOAIENG-20368 
=> fix indent bug in e2e raw setup

CONTRIBUTING.md, docs/odh/fetch-upstream-release.md
This is a guide outlining the process to fetch a new upstream version to ODH fork.
Related to: https://issues.redhat.com/browse/RHOAIENG-23576
=> Add guide to create a new branch from an upstream release

config/overlays/odh/inferenceservice-config-patch.yaml, config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
[RHOAIENG-24705](https://issues.redhat.com/browse/RHOAIENG-24705)
To allow openshift route timeout to be configurable by setting the `haproxy.router.openshift.io/timeout` in an ISVC, we must prevent this annotation from being propagated to created deployments or knative services to avoid unneeded reconciliation of those resources. This PR adds this annotation to the `serviceAnnotationDisallowedList` in the `inferenceservice-config` configmap.
- …
=> Disallow Propagation of haproxy.router.openshift.io/timeout Annotation

config/overlays/odh/params.env
Reference the right images, for nightly builds.
Part of https://issues.redhat.com/browse/RHOAIENG-25714
=> Fix references to ODH images in params.env

python/huggingface_server_cpu.Dockerfile, python/huggingfaceserver/Makefile, python/huggingfaceserver/huggingfaceserver/request_logger.py
Cherry picks https://github.com/kserve/kserve/pull/4516 and https://github.com/kserve/kserve/pull/4514
Re-running failed tests
/rerun-all - rerun all failed workflows.
/rerun-workflow <workflow name> - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.
=> [Cherry pick] Python test fixes from upstream

docs/samples/explanation/alibi/alibiexplainer/poetry.lock, docs/samples/explanation/alibi/alibiexplainer/pyproject.toml, python/aiffairness/poetry.lock, python/artexplainer/poetry.lock, python/custom_model/poetry.lock, python/custom_tokenizer/poetry.lock, python/custom_transformer/poetry.lock, python/huggingfaceserver/poetry.lock, python/kserve/poetry.lock, python/lgbserver/poetry.lock, python/paddleserver/poetry.lock, python/pmmlserver/poetry.lock, python/sklearnserver/poetry.lock, python/test_resources/graph/error_404_isvc/poetry.lock, python/test_resources/graph/success_200_isvc/poetry.lock, python/xgbserver/poetry.lock
Fixes #
- Logs
**Checklist**:
```release-note
```
- …
=> [RHOAIENG-26924] - CVE-2025-43859: h11 HTTP Request Smuggling

config/overlays/odh/inferenceservice-config-patch.yaml, config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
Cherry pick commit 9f8600bfc6b27d7e697d54ccd676e4ba35fc7b95
adding haproxy.router.openshift.io/timeout to serviceAnnotation disall owed list to prevent propagation to deployment or knative service (#637)
Fixes #
- Logs
1. Please confirm that if this PR …
=> [Cherry Pick] Ignore Openshift Route Timeout Annotation

config/llmisvc/config-llm-template.yaml, config/llmisvc/kustomization.yaml, docs/samples/llmisvc/opt-125m/llm-inference-service-facebook-opt-125m-cpu.yaml
Add `kserve-config-llm-template` well-known preset
=> Add well-know preset for single node

pkg/controller/llmisvc/workload.go
As controller-runtime reads are from the cache, it can happen that after creating deployment the cache will be out of sync with kube-apiserver leading to following error and re-triggering entire reconcile:
```
2025-06-25T08:51:21+02:00	ERROR	LLMInferenceService	Failed to reconcile LLMInferenceService	{"controller": "llminferenceservice", "controllerGroup": "serving.kserve.io", "controllerKind": "LLMInferenceService", "LLMInferenceService": {"name":"test-llm","namespace":"test-llm-test"}, "namespace": "test-llm-test", "name": "test-llm", "reconcileID": "0e1d3405-978a-4bac-899c-817e1ffdfa23", "error": "failed to reconcile workload: failed to reconcile main workload: failed to get current deployment test-llm-test/test-llm-kserve: Deployment.apps \"test-llm-kserve\" not found"}
```
Instead we …
=> fix(deployment): retries for status update

Makefile, hack/deploy_dev_llm.sh
When using Kustomize to create both a CRD (CustomResourceDefinition) and a CR (Custom Resource) at the same time, it's common to encounter an error like "no matches for kind..." because the CRD has not yet been registered with the API server when the CR is applied.
I split the CRD into a separate Kustomize deployment and added a step in the script to install the ko CLI.
```
kind create cluster
#example => export KO_DOCKER_REPO=quay.io/jooholee 
export KO_DOCKER_REPO=XXXX
make deploy-dev-llm 
```
Fixes #
**Feature/Issue …
=> follow up deployment script for llmd

pkg/controller/llmisvc/DEV.md
This adds the required command to successfully run the provided sample in DEV.md on a minikube cluster as an alternative to kind.
N/A
Dev docs
**Checklist**:
- [N/A] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [N/A] Have you linked the JIRA issue(s) to this PR?
=> Add instructions for dev setup of LLMIsvc on minikube

pkg/controller/llmisvc/controller.go
- Add enqueue logic for un-managed Gateway(s)
- Add well-known presets enqueue logic
=> Improve enqueue logic for Gateway and well-known presets

config/llmisvc/config-llm-decode-template.yaml, config/llmisvc/config-llm-decode-worker-data-parallel.yaml, pkg/controller/llmisvc/config_presets_test.go, pkg/controller/llmisvc/workload.go, pkg/controller/llmisvc/workload_multi_node.go, pkg/controller/llmisvc/workload_single_node.go
See `https://github.com/llm-d/llm-d-inference-scheduler/issues/242`
=> RHOAIENG-30217: Enable SSRF protection for sidecar

python/kserve/kserve/__init__.py
Backport of https://github.com/kserve/kserve/pull/4604
=> fix(deps): adds missing LLMInferenceService types for python

config/llmisvc/config-llm-decode-template.yaml, config/llmisvc/config-llm-decode-worker-data-parallel.yaml, config/llmisvc/config-llm-prefill-template.yaml, config/llmisvc/config-llm-prefill-worker-data-parallel.yaml, config/llmisvc/config-llm-scheduler.yaml, config/llmisvc/config-llm-template.yaml, config/llmisvc/config-llm-worker-data-parallel.yaml, pkg/controller/llmisvc/DEV.md, pkg/controller/llmisvc/config_merge.go, pkg/controller/llmisvc/config_presets_test.go, pkg/controller/llmisvc/controller_int_test.go, pkg/controller/llmisvc/sample.go, pkg/controller/llmisvc/scheduler.go, pkg/controller/llmisvc/workload_single_node.go, pkg/controller/llmisvc/workload_tls_self_signed.go, test/scripts/gh-actions/setup-deps.sh
=> RHOAIENG-30166: Upgrade to llm-d 0.2

config/overlays/odh/config-llm-decode-template-patch.yaml, config/overlays/odh/config-llm-decode-worker-data-parallel-patch.yaml, config/overlays/odh/config-llm-scheduler-patch.yaml, config/overlays/odh/kustomization.yaml, config/overlays/odh/params.env, config/overlays/odh/params.yaml
For konflux, we need to use params.env file for changing images. This pr add llmd scheduler/routing sidecar images to params.env. For llm-d core, I could not find right images so I will follow up later.
Moreover, for now I am using odh-v2.33 because Quay is down and nobody can create tag. Later it should be `0.2`
Fixes #
Please also list any relevant details …
=> add llmd scheduler/routing sidecar image to params.env

test/overlays/llm-istio-experimental/istiod.yaml
generate manifest by upstream istio helm (It only changed resources)
Fixes #
- Logs
**Checklist**:
```release-note
```
**Re-running …
=> update istiod yaml file to increase resources

config/crd/external/gie/kustomization.yaml, config/overlays/odh/kustomization.yaml
This add GIE CRD 0.5.0.
Fixes #
- Logs
**Checklist**:
```release-note
```
- `/rerun-all` - rerun all failed …
=> add GIE CRD

docs/samples/llmisvc/opt-125m/llm-inference-service-pd-facebook-opt-125m-cpu.yaml
Aligns doc sample with latest release version used in presets.
=> chore: updates router sidecar image

Makefile, config/llmisvc/gie.yaml, config/llmisvc/kustomization.yaml, config/overlays/odh/kustomization.yaml
We can't use remote references as it doesn't work on disconnected and it's sub-optimal
=> Prefetch GIE CRDs

config/configmap/inferenceservice.yaml, config/overlays/odh/inferenceservice-config-patch.yaml, config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml, config/overlays/test/configmap/inferenceservice.yaml, pkg/controller/llmisvc/fixture/required_resources.go
This PR unblocks model deployments using oci images.
root cause of the issue is the `uidModelcar` value we have hard coded in the `inferencservice-config` configmap. We have it hard coded as `1010`
Doing some research - "During the creation of a project or namespace, OpenShift assigns a User ID (UID) range, a supplemental group ID (GID) range, and unique SELinux MCS labels to the project or namespace."
What is happening here is that when the namespace gets created to run tests within, that namespace is assigned a UID range that this hard coded value of `1010` does not fall within
Removing the `uidModelcar` value from the `inferenceservice-config` configmap when running in openshift solves this issue.
**Which issue(s) this PR fixes** *(optional, in …
=> remove uidModelcar value from inferenceservice-config configmap inodh

pkg/controller/llmisvc/controller.go
This is the default gatewayClass by Openshift
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
name: openshift-default
annotations:
unsupported.do-not-use.openshift.io/ossm-channel: stable
unsupported.do-not-use.openshift.io/ossm-version: servicemeshoperator3.v3.1.0 
unsupported.do-not-use.openshift.io/ossm-catalog: istio-catalog
unsupported.do-not-use.openshift.io/istio-version: v1.26.2
spec:
controllerName: "openshift.io/gateway-controller/v1"
```
The controllerName is different that we have now so this pr update the name. Without this, destinationRule is not created by [this code](https://github.com/opendatahub-io/kserve/blob/release-v0.15/pkg/controller/llmisvc/workload_tls_self_signed_istio.go#L82)
**Which issue(s) this …
=> update gatewayclass controller name

pkg/controller/llmisvc/DEV.md
OCP 4.19.2 with fix (openshift/cluster-ingress-operator#1249) have a feature to support gateway. 
This PR explain how to enable OSSM3.
Fixes #
- Logs …
=> Add a guide how to use OSSM by OCP

pkg/controller/llmisvc/DEV-authz.md
As per title, it adds authentication for LLMIsvc
=> Apply Authentication for LLMISVC on OpenShift

pkg/controller/llmisvc/controller_int_test.go, pkg/testing/meta_matchers.go
=> chore: renames controlled-by owner assertion

pkg/controller/llmisvc/controller_workload_storage_int_test.go, pkg/controller/llmisvc/workload_storage.go
[RHOAIENG-33463](https://issues.redhat.com/browse/RHOAIENG-33463)
This PR injects the ca bundle into the storage-init container for llmisvcs utilizing s3 based storage connections. The ca bundle is injected based on the configuration defined in the service account or secret annotations or in the inferenceservice-config configmap.
**Checklist**:
```release-note
CA Bundle Injection for LLMISVCs with S3 storage
```
**Re-running …
=> injecting ca bundle for s3 storage on llmisvc reconciliation
