.github/workflows/agent-docker-publish.yml, .github/workflows/go.yml, .github/workflows/kserve-controller-docker-publish.yml, .github/workflows/router-docker-publish.yml, .github/workflows/storage-initializer-docker-publisher.yml, README.md
* Workflows are changed to push to Quay.io.
* The go.yml workflow is changed to omit updating the coverage badge (we don't have one, for now).
* The README.md file is updated to right ODH urls.
**Which issue(s) this PR fixes** 
Fixes #27 
```release-note
NONE
```
=> Adapt GH-workflows to correctly push to ODH container repositories

config/overlays/odh/kustomization.yaml, config/overlays/odh/remove-namespace.yaml, config/overlays/odh/user-cluster-roles.yaml
Augments the `default` profile with some changes expected by an ODH installation:
* Removes the `Namespace` CR, because the ODH operator does not expect such resource. The Namespace is expected to be created in advance to later create a KfDef on it, where resources are going to be installed.
* Adds cluster roles, to extend the cluster's default user-facing roles with KServe privileges.
* Changes from the following PR are being moved  here: opendatahub-io/odh-manifests#887
* Related to: opendatahub-io/odh-manifests#884
* Related to: opendatahub-io/odh-manifests#887
**Feature/Issue …
=> Add ODH overlay

.github/workflows/qpext-docker-publish.yml
This adapts the _Queue Proxy Extension Docker Publisher_ workflow to build an publish a container image to Quay. 
Related #15 
A test run can be found here: https://github.com/israel-hdez/kserve/actions/runs/5957673480
```release-note
NONE
```
=> [v0.11] Adapt qpext workflow for OpenDataHub

python/kserve/kserve/storage/storage.py
This is a cherry-pick for https://github.com/kserve/kserve/pull/3172 and it is already merged into [downstream](https://github.com/red-hat-data-services/kserve/pull/24)
~~~
Test instruction: https://github.com/opendatahub-io/caikit-tgis-serving/tree/main/demo/kserve/scripts
export TARGET_OPERATOR=odh
export CHECK_UWM=false
oc edit cm inferenceservice-config -n redhat-ods-applications
...
storageInitializer: |-
{
"image" : "quay.io/jooholee/storage-initializer@sha256:6b6252e6a1df2a1140be4ab1f8b68b159e448aaf27b8f3212d19daeb44381af4",
...
oc delete pod -n redhat-ods-applications -l control-plane=kserve-controller-manager --force --grace-period=0
#add annotate to the storage-config secret
oc annotate secret/storage-config  serving.kserve.io/s3-verifyssl="0" -n kserve-demo
oc delete pod …
=> cherry-pick fix-3171

config/overlays/odh/inferenceservice-config-patch.yaml, config/overlays/odh/kustomization.yaml, config/overlays/odh/params.env, config/overlays/odh/params.yaml, python/storage-initializer.Dockerfile
Open Data Hub operator v2 is going to be consuming Kustomize manifests from component repos, and `odh-manifests` repo is going to be archived.
This is moving/copying artifacts from `odh-manifests` into an already existent odh overlay. With these changes, the overlay can be directly consumed by ODH-operator v2.
Additionally, this should fix a build issue in the storage-initializer.
Related #72 
You can test in two ways:
Simply, build with kustomize:
```sh
kustomize build config/overlays/odh
```
It should render the manifests without error.
Use the following YAML in the DSC:
```yaml
spec:
components:
kserve:
devFlags:
manifests:
- contextDir: config
sourcePath: overlays/odh
uri: …
```
=> Preparation for odh-opeartor v2

config/overlays/odh/inferenceservice-config-patch.yaml
Partial revert of
https://github.com/opendatahub-io/odh-manifests/pull/916, because https://github.com/opendatahub-io/odh-model-controller/pull/84 has been completed.
Testing instructions are the same as in #107, but use `uri: 'https://github.com/israel-hdez/kserve/tarball/enable-istio-vh` in `devFlags`.
=> Enable Istio Virtual Host

config/default/kustomization.yaml
Remove webhook from inferenceservice crd in kserve as a patch as a workaround for the CRD conflict resulting in not being able to install modelmesh and kserve together.
Fixes https://github.com/opendatahub-io/opendatahub-operator/issues/573
DSC Spec: 
```
spec:
components:
codeflare:
devFlags: …
```
=> remove webhookClientConfig from inferenceservice crd of kserve

config/overlays/odh/kustomization.yaml, config/overlays/odh/set-resources-manager-patch.yaml
It increased the `limit.resource` of kserve controller manager has been increased.
Fixes #https://github.com/opendatahub-io/kserve/issues/126
- This does not change the source so it does not need any tests.
**Checklist**:
```release-note
```
=> Increase kserve controller limit resources(cpu/memory)

python/kserve/kserve/storage/storage.py
This is cherry-pick of https://github.com/kserve/kserve/pull/3267
Fixes #
Test Step:
1. install opendatahub operator and kserve
2. The detail guide is here: https://docs.google.com/document/d/1pf0x1geayFr-06lAQKr96ynVsnOCcpgmAfbgoHgg8AI/edit
*Scale down odh operator pod*
~~~
oc scale …
=> [Cherry-Pick] Support verify variable with storage-config json style (fix-3263) 

python/kserve/kserve/storage/storage.py
This is cherry-pick of https://github.com/kserve/kserve/pull/3267
Fixes #
Test Step:
1. install opendatahub operator and kserve
2. The detail guide is here: https://docs.google.com/document/d/1pf0x1geayFr-06lAQKr96ynVsnOCcpgmAfbgoHgg8AI/edit
*Scale down odh operator pod*
~~~
oc scale …
=> [Cherry-pick] Support verify variable with storage-config json style (fix-3263)

test/scripts/openshift-ci/deploy.ossm.sh, test/scripts/openshift-ci/deploy.serverless.sh
Also, remove Mesh-related components that are not needed.
Should fix CI failures for openshift/release#46506
=> Use ThirdParty tokens for CI, for compatibility with ROSA-Hosted clusters

config/configmap/inferenceservice.yaml, config/overlays/odh/params.env, docs/samples/cabundle/README.md, pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/controller.go, pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/cabundleconfigmap/cabundle_configmap_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/cabundleconfigmap/cabundle_configmap_reconciler_test.go, pkg/credentials/s3/s3_secret.go, pkg/credentials/s3/utils.go, pkg/credentials/s3/utils_test.go, pkg/credentials/service_account_credentials.go, pkg/webhook/admission/pod/storage_initializer_injector.go, pkg/webhook/admission/pod/storage_initializer_injector_test.go, python/kserve/kserve/storage/storage.py
Fixes #https://github.com/kserve/kserve/pull/3250
Cherry-pick
You can find original tests from this PR(https://github.com/kserve/kserve/pull/3250).
I updated the test scenario according to the platform change.
**Pre-requirements**
- install openshift cluster (above 4.12)
- login to openshift …
=> [Cherry Pick - 3250] feat: CA bundle mount options for storage initializer

charts/kserve-resources/templates/configmap.yaml, charts/kserve-resources/values.yaml, config/configmap/inferenceservice.yaml, pkg/apis/serving/v1beta1/configmap.go, pkg/apis/serving/v1beta1/openapi_generated.go, pkg/apis/serving/v1beta1/swagger.json, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go, python/kserve/docs/V1beta1IngressConfig.md, python/kserve/kserve/models/v1beta1_ingress_config.py, python/kserve/kserve/storage/storage.py, python/kserve/kserve/storage/test/test_s3_storage.py
Cherry pick:
- kserve/kserve#3259 - Fix python library around environment variables
- kserve/kserve#3371 - By default, mount PVC volumes directly
- kserve/kserve#3436 - Add capability to disable ingress creation in RawDeployment mode
=> [Cherry pick] fixes to current release branch 0.11.1

pkg/constants/constants.go, pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1beta1/inferenceservice/controller.go, pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/utils/utils.go
Cherry-pick of b6bf6aa
Related to: https://issues.redhat.com/browse/RHOAIENG-3474
=> Enhance controller setup based on available CRDs

python/storage-initializer.Dockerfile
Fixes CVE-2024-24762 - Regular Expression Denial of Service (ReDoS) Remove the fastapi when this is addressed:  https://issues.redhat.com/browse/RHOAIENG-3894 or ray releses a new version that removes the fastapi version pinning and it gets updated on KServe
Fixes #
- Logs
**Special notes for …
=> [RHOAIENG-3551] - fastapi - Regular Expression Denial of Service (ReDoS)

config/overlays/odh/set-resources-manager-patch.yaml
The increased memory limit is for the controller pod to work normally in clusters having 9k+ secrets.
**Which issue(s) this PR fixes** 
Fixes https://issues.redhat.com/browse/RHOAIENG-3996
With KServe deployed:
* Use a script from @skonto available in this gist: https://gist.github.com/skonto/188b2c45c5af449629caaa69a190392c, with a minor modification: edit line 3 to NC=64
* Try to deploy an  InferenceService (any ISVC simple should work).
* Without the patch, observe an OOMKill.
* With the patch, the pod should not die.
=> [v0.11.1] Increase memory limit of kserve-controller pod

python/storage-initializer.Dockerfile
Fixes CVE-2024-24762 - Regular Expression Denial of Service (ReDoS) Remove the fastapi when this is addressed:  https://issues.redhat.com/browse/RHOAIENG-3894 or ray releses a new version that removes the fastapi version pinning and it gets updated on KServe
Cherry-picks d779e7e065e85d2a00b0328a5e303e9cb9d80595
=> [cherry-pick][RHOAIENG-3551] - fastapi - Regular Expression Denial of Service (ReDoS)

config/overlays/odh/set-resources-manager-patch.yaml
The increased memory limit is for the controller pod to work normally in clusters having 9k+ secrets.
**Which issue(s) this PR fixes** 
Related to https://issues.redhat.com/browse/RHOAIENG-3996
With KServe deployed:
* Use a script available in this gist: https://gist.github.com/skonto/188b2c45c5af449629caaa69a190392c, with a minor modification: edit line 3 to NC=64
* Try to deploy an  InferenceService (any ISVC simple should work).
* Without the patch, observe an OOMKill.
* With the patch, the pod should not die.
=> Increase memory limit of kserve-controller pod

cmd/manager/main.go
In #233 an enhancement was done to KServe controllers to watch resources based on available CRDs.
A similar change in the setup of the manager was overlooked: it is also needed to add schemas to the manager based on available CRDs rather than only the values in the inferenceservice-config ConfigMap. This would keep both manager setup and controller setup in sync with regards schemas and watches around the CRDs.
This is, basically, a cherry-pick of commti 5180ec56f25186ef643bb909adaf4784fe337bb5 from upstream PR (not merged yet).
Fixes https://issues.redhat.com/browse/RHOAIENG-4196
**Type of …
=> [v0.11.1] Fix controller setup - add schemas based on CRDs available

config/overlays/test/configmap/inferenceservice-openshift-ci-raw.yaml, python/kserve/kserve/models/v1beta1_inference_service.py, test/e2e/predictor/test_raw_deployment.py, test/e2e/transformer/test_collocation.py, test/e2e/transformer/test_raw_transformer.py, test/scripts/openshift-ci/run-e2e-tests.sh
Since ODH would support KServe's RawDeployment mode, this modifies the scripts around OpenShift-ci setup to be possible to run RawDeployment-related E2Es.
The run-e2e-tests.sh script is modified to exclude installation of Service Mesh and Serverless, when RawDeployments E2Es are requested to run. A supporting file inferenceservice-openshift-ci-raw.yaml was added to patch KServe's configuration to use RawDeployment mode by default and to use OpenShift Ingress when exposing Inference Services.
Since the E2Es use some annotations in the InferenceService, changes done to the v1beta1_inference_service.py file in commit ecff079 were reverted. As an alternative, the `enablePassthrough` annotation was moved to the ServingRuntime resources. This is not only …
=> Add capability to run RawDeployment E2Es in OpenShift-ci

Makefile, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go, test/e2e/logger/test_logger.py, test/e2e/logger/test_raw_logger.py
Cherry-picks https://github.com/opendatahub-io/kserve/pull/280
=> [RHOAIENG-5073] - Routing and Headless Service Support in KServe Raw Mode Deployment

python/kserve/kserve/protocol/infer_type.py, python/kserve/test/test_infer_type.py
This brings the pending commits from upstream `v0.12.0` tag to ODH `release-v0.12.0` branch.
The ODH `release-v0.12.0` branch was cut to the closest commit to upstream `v0.12.0` tag. This brings the additional commits present in upstream `v0.12.0` tag to ODH `release-v0.12.0` branch to make the branch equivalent to upstream v0.12.0 release.
**Which issue(s) this PR fixes** 
Related to https://issues.redhat.com/browse/RHOAIENG-4180
=> Prepare ODH's v0.12.0 branch cut

.github/workflows/create-release-tag.yml, .github/workflows/odh-create-release-tag.yml
Automate ODH Release Process for Kserve repos
Fixes #[RHOAIENG-2732](https://issues.redhat.com/browse/RHOAIENG-2732)
=> Create Workflow for release and tag with Changelog

pkg/apis/serving/v1beta1/inference_service_validation.go, pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/components/explainer.go, pkg/controller/v1beta1/inferenceservice/components/predictor.go, pkg/controller/v1beta1/inferenceservice/components/transformer.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go
Cherry-pick of kserve/kserve#3086
=> [v0.11.1] Allow disabling creation of the HPA in raw deployment mode (#3086)

python/storage-initializer.Dockerfile
As the Ray Serve latest release removed the hard dependency of old fastapi version we can now remove the workaround from the Storage Initializer Container Image.
```release-note
NONE
```
=> [RHOAIENG-4617] - follow up - remove hardcoded fastapi from Dockerfile

.github/workflows/storage-initializer-docker-publisher.yml
There is an error in the storage-initializer-docker-publisher workflow where a string is being used, but should be a variable. On PR merges, this is causing an error when trying to push the docker image of the storage initializer.
This is fixing the issue by properly using the variable.
=> Fix storage-initializer-docker-publisher workflow

pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler_test.go
Cherry-picks https://github.com/kserve/kserve/pull/3650.
=> [RHOAIENG-6878][Cherry-pick][RHOAI-2.10] fix: HPA equality check should include annotations (#3650)

Dockerfile, agent.Dockerfile, python/storage-initializer.Dockerfile, router.Dockerfile
Fixes https://issues.redhat.com/browse/RHOAIENG-6506  
`Note: Replaced existing Dockerfiles because that file is what Konflux uses to build the images. Also, this will help track any changes to the upstream dockerfile because it will create a merge-conflict (as opposed to maintaining a separate `Dockerfile.ubi8` file). 
- tested `podman build` succeeds …
=> replace upstream Dockerfiles with ubi dockerfiles.

docs/odh/authorino-setup-manual.md, docs/odh/authorization.md
Fixes #
**Checklist**:
-->
```release-note
NONE
```
=> Docs for authorization feature

charts/kserve-resources/README.md, charts/kserve-resources/templates/configmap.yaml, charts/kserve-resources/values.yaml, config/configmap/inferenceservice.yaml, config/overlays/odh/inferenceservice-config-patch.yaml, config/overlays/test/configmap/inferenceservice-disable-istio.yaml, config/overlays/test/configmap/inferenceservice-ingress.yaml, config/overlays/test/configmap/inferenceservice.yaml, hack/violation_exceptions.list, pkg/apis/serving/v1beta1/configmap.go, pkg/apis/serving/v1beta1/configmap_test.go, pkg/apis/serving/v1beta1/openapi_generated.go, pkg/apis/serving/v1beta1/swagger.json, pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go, pkg/controller/v1beta1/inferenceservice/suite_test.go, python/kserve/docs/V1beta1IngressConfig.md, python/kserve/kserve/models/v1beta1_ingress_config.py, python/kserve/test/test_v1beta1_ingress_config.py
Cherry-pick of kserve/kserve#3737
=> Allow KServe to have its own local gateways for Serverless mode

pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
For upstream, the protocol for inferenceservice endpoint is hardcoded to`http` but for ODH/RHOAI, it uses `https` everywhere. Therefore, it should be changed to `https`.
Fixes # https://issues.redhat.com/browse/RHOAIENG-10064
Deploy OpenDataHub KServe with the following DSC
DSC:
~~~
spec: …
=> set protocol https for .Status.Address.URL

.github/workflows/agent-docker-publish.yml, .github/workflows/kserve-controller-docker-publish.yml, .github/workflows/qpext-docker-publish.yml, .github/workflows/router-docker-publish.yml
*What this PR does / why we need it**:
This PR fixes the build jobs for some of the images like kserve-controller, qpext, router, agent.
Fixes https://github.com/opendatahub-io/kserve/issues/389
The image build jobs were failing because go-toolset 1.21 version image is not available for linux/arm/v7 architecture.
So, for now removed that architecture from the GH workflows so that the build job passes and pushed the images for other architectures.
- Logs
1. Please confirm that if this PR changes …
=> Removed arm/v7 to make the jobs working again for now

pkg/controller/v1beta1/inferenceservice/controller.go
Cherry-pick of kserve/kserve#3753
=> [release-v0.12.1]  inferenceservice controller: fix error check in Serverless mode

config/overlays/odh/user-cluster-roles.yaml
One of the aggregate roles were using `kubeflow.org` in the API groups, which is incorrect.
This fixes the manifests to use the right API group.
Related to opendatahub-io/odh-model-controller#255
=> Fix apiGroups in aggregate roles on manifests

pkg/webhook/admission/pod/storage_initializer_injector.go, pkg/webhook/admission/pod/storage_initializer_injector_test.go
Cherry-pick of https://github.com/kserve/kserve/pull/3932
**Which issue(s) this PR fixes**:
Fixes https://issues.redhat.com/browse/RHOAIENG-12539
(TODO)
**Checklist**:
- [N/A] Have you made corresponding changes to the documentation?
=> Modelcar race condition mitigation with an init container

python/kserve/poetry.lock
chore:  It is not a real fix, we just need to update the poetry.lock files
so the dependency version gets updated, in this case the cryptography
one was updated as expected to the suggested one.
Fixes #
- Logs
1. Please confirm that if this PR changes any …
=> [RHOAIENG-13712] [CVE-2024-6119] - KServe - Type Confusion

docs/odh/oci-model-storage.md
Documentation on using OCI images for model storage (modelcars)
https://issues.redhat.com/browse/RHOAIENG-13446
**Checklist**:
- [N/A] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
=> Documentation on using OCI images for model storage (modelcars)

cmd/agent/main.go, pkg/constants/constants.go, pkg/logger/handler.go, pkg/logger/handler_test.go, pkg/logger/types.go, pkg/logger/worker.go, pkg/webhook/admission/pod/agent_injector.go, pkg/webhook/admission/pod/agent_injector_test.go
This PR adds support for TLS in Inference Loggers.
It adds two new optional fields to the global ConfigMap: `tlsBundle` and `tlsCertName`.
If a ConfigMap matching `tlsBundle` is present in the Inference Service's namespace, it will be mounted as a volume on the agent. 
* If the logger's endpoint protocol is of type `https`, the logger will use the CA cert specified with `tlsCertName` to configure the transport.
* If TLS is configured in ConfigMap, but the bundle is not available or the CA cert is not found, the logger will continue to behave as before this PR (no TLS transport configured)
* If the logger's endpoint protocol is of type `http`, the inference logger will behave as previously
_why we need it_
The current implementation does not …
=> [Cherry pick] Add TLS support for Inference Loggers (kserve#3863) 

.github/workflows/e2e-test.yml, config/crd/external/datasciencecluster.opendatahub.io_datascienceclusters.yaml, config/crd/external/dscinitialization.opendatahub.io_dscinitializations.yaml, config/crd/external/kustomization.yaml, config/default/kustomization.yaml, config/overlays/odh/set-resources-manager-patch.yaml, config/overlays/test/configmap/inferenceservice-openshift-ci-serverless.yaml, config/overlays/test/dsc.yaml, config/overlays/test/dsci.yaml, config/overlays/test/kustomization.yaml, test/e2e/common/utils.py, test/e2e/custom/test_custom_model_grpc.py, test/e2e/custom/test_ray.py, test/e2e/explainer/test_art_explainer.py, test/e2e/predictor/test_autoscaling.py, test/e2e/predictor/test_grpc.py, test/e2e/predictor/test_lightgbm.py, test/e2e/predictor/test_pmml.py, test/e2e/predictor/test_raw_deployment.py, test/e2e/predictor/test_response_headers.py, test/e2e/predictor/test_torchserve.py, test/e2e/predictor/test_xgboost.py, test/scripts/gh-actions/check-poetry-lockfile.sh, test/scripts/openshift-ci/run-e2e-tests.sh
- [Reduce E2Es dependency on CI environment (2) (](https://github.com/opendatahub-io/kserve/commit/37be2411b462687026686abac8d7bdb7c79c9cd2)https://github.com/kserve/kserve/pull/4008[)](https://github.com/opendatahub-io/kserve/commit/37be2411b462687026686abac8d7bdb7c79c9cd2)
- [Revert 'Increase memory limit of kserve-controller pod'](https://github.com/opendatahub-io/kserve/commit/5f1ff0498b6a101c50ba6b6201bd45b5cba0642a)
- [Fix issues after 0.14.0 sync (](https://github.com/opendatahub-io/kserve/commit/9f46725f5c2802959d6bfd7a986acef8c17aede2)https://github.com/opendatahub-io/kserve/pull/424[)](https://github.com/opendatahub-io/kserve/commit/9f46725f5c2802959d6bfd7a986acef8c17aede2)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
=> [Cherry-pick] To fix e2e test, cherry pick commits to 0.14 release banch

Dockerfile, agent.Dockerfile, go.mod, router.Dockerfile
This upgrade golang version. The acceptable result is passing all gitaction ci. 
If it builds all the images with a new version, it is ok to be merged
Fixes #
- Logs
1. Please confirm that if this PR changes any image versions, then that's the sole change …
=> upgrage golang from 1.21 to 1.22

pkg/constants/constants.go
chore:	Adds the `security.opendatahub.io/enable-auth` label to the ServiceAnnotationDisallowedList
to prevents the model to be rolled out in case the auth is disabled / enabled
- install the Authorino operator (tech preview version)
Update the DSC:
```yaml
spec:
components:
codeflare:
managementState: Removed
kserve:
devFlags:
manifests:
- contextDir: config
sourcePath: ''
uri: 'https://github.com/spolti/kserve/tarball/test1234'
managementState: Managed
serving:
ingressGateway:
certificate:
secretName: knative-serving-cert
type: SelfSigned
managementState: Managed
name: knative-serving
trustyai:
managementState: Removed
ray:
managementState: Removed
kueue:
managementState: Removed
workbenches:
managementState: Managed
dashboard:
managementState: Managed
modelmeshserving:
managementState: …
```
=> [RHOAIENG-11034] - Disabling Authorino Token Authorization forces a Model Pod to rollout

pkg/constants/constants.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
This changes kserve-controller to mount the OpenShift Service CA bundle into kserve-router container and a configures it to trust the bundle. This affects InferenceGraph deployed in Serverless mode.
With these changes, InferenceGraphs will work correctly when deployed without an Istio sidecar.
These changes are needed because in ODH the InferenceServices are secured with TLS. The internal endpoints (which are the ones InferenceGraph uses) are using OpenShift service serving certificates.
Related to: https://issues.redhat.com/browse/RHOAIENG-13448
Please delete options that …
=> Trust OpenShift service CA in kserve-router

cmd/router/main.go, pkg/constants/constants.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go, pkg/controller/v1alpha1/inferencegraph/raw_ig.go
Cherry-pick the following PRs:
* kserve/kserve#4031
* opendatahub-io/kserve#426
Fixes https://issues.redhat.com/browse/RHOAIENG-13448
=> [v0.14] Cherry-pick Inference Graph stabilizations

test/scripts/openshift-ci/kustomization.yaml
Use the odh-model-controller incubating branch as part of the new odh-model-controller branching strategy
=> Use odh-model-controller incubating branch

.github/workflows/create-release-tag.yml
Updated the create-release-tag.yaml file to grab the old release tag based on creation date.
=> Fix old tag grab

.github/workflows/create-release-tag.yml
Updated the create-release-tag.yaml file to grab the old release tag based on creation date. 
- Cherry picked from https://github.com/opendatahub-io/kserve/pull/452
=> [Cherry-pick] Fix old tag grab

pkg/constants/constants.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
Implementation of authentication for InferenceGraphs using Serverless mode will use ServiceMesh with Authorino (like InferenceServices case). For this, an Istio AuthorizationPolicy is applied mesh-wide. The AuthorizationPolicy uses a static label selector that is expected to be present on all Pods that require to be protected.
Currently, the InferenceGraph does not have a static label that can be used.
This PR is adding the `serving.kserve.io/kind: InferenceGraph` to pods that belong to InferenceGraph to properly protect them per user request.
Related to: …
=> Add well-known label to InferenceGraphs

pkg/apis/serving/v1beta1/inference_service_status.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
**What this PR does / why we need it**: 
- Fix bug regarding inconsistent schemas in isvc.status.url and isvc.status.address.url for rawdeployment
- Remove component URL temporarily (follow up JIRA to add them back correctly : https://issues.redhat.com/browse/RHOAIENG-17765) 
Fixes # https://issues.redhat.com/browse/RHOAIENG-16851  …
=> [RHOAIENG-16851] - Rawdeployment bug fixes

config/overlays/odh/inferenceservice-config-patch.yaml
Cherry-pick of #467.
Related to: https://issues.redhat.com/browse/RHOAIENG-17827
=> [master] Enable forwarding Authorization header in InferenceGraphs

cmd/manager/main.go, config/webhook/manifests.yaml, pkg/apis/serving/v1beta1/inference_service_validation.go, pkg/webhook/validation/inferenceservice/inferenceservice_webhook_test.go, pkg/webhook/validation/inferenceservice/webhook_suite_test.go
InferenceGraphs can reference InferenceServices to create an inference pipeline using multiple models. Deleting an InferenceService that is being referenced by an InferenceGraph can turn unusable the InferenceGraph.
This adds a validation to prevent deletion of InferenceServices that are being used in InferenceGraphs.
Fixes https://issues.redhat.com/browse/RHOAIENG-17829
1. Create some InferenceServices
2. Create an InferenceGraph that uses some of the InferenceServices
3. Try to delete an InferenceService that is used by the InferenceGraph
* The InferenceService should be blocked from being deleted
4. Try to delete an InferenceService that is NOT used by the InferenceGraph
* The …
=> On InferenceService deletion, validate no references to it

pkg/agent/storage/https.go
[RHOAIENG-16692](https://issues.redhat.com/browse/RHOAIENG-16692) Cherry-pick of https://github.com/kserve/kserve/pull/4205 
=> [Cherry-Pick] Cleanup the filepath in createNewFile to avoid path traversal issue

.github/workflows/odh-create-release-tag.yml, config/overlays/odh/params.env
[RHOAIENG-18934](https://issues.redhat.com/browse/RHOAIENG-18934) Fixes the old_tag_name and uses the v0.14-latest tag from params.env 
=> Fix the tags used in the ODH release process on release-v0.14

.github/workflows/odh-create-release-tag.yml
[RHOAIENG-18934](https://issues.redhat.com/browse/RHOAIENG-18934) Fixes the `old_tag_name` and uses the `latest` tag from params.env 
=> Fix the tags used in the ODH release process on master

config/manager/manager.yaml
For in-place upgrades the manifests of the new version are applied in a cluster where KServe may already be installed. The old version of the kserve-controller is terminated and the new version is deployed.
The default strategy is Rolling. This has the consequence that during an in-place upgrade, there will be two different versions of kserve-controller running in parallel. Most importantly, the two instances will be running with different configs, which include references to different versions of kserve-agent, kserve-router, storage-initializer, etc. During an in-place upgrade, the new version of the controller will upgrade the deployed models to use the new versions of the images. However, since the old version of kserve-controller is running in …
=> Better compatibility with in-place upgrades

test/scripts/openshift-ci/run-e2e-tests.sh, test/scripts/openshift-ci/setup-e2e-tests.sh
Related to [RHOAIENG-14604](https://issues.redhat.com/browse/RHOAIENG-14604) 
Moves the cluster installation steps into a new script so that they may be easily commented out when debugging the e2e tests locally. 
=> Split the e2e test cluster setup into a new script

config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
Following up with comments here: https://github.com/opendatahub-io/kserve/pull/491#discussion_r1947222525
The reverts commit 2a917eafe8ec716254423c9079f05aaa7f59ab0f (PR #491), which changed the configuration of the Deployment for the manager to use `Recreate` strategy. Such change was for better compatibility for in-place upgrades (see description of PR #491).
Instead of changing the Deployment strategy, this is enabling leader election in the manager. The leader election also solves the issues mentioned in PR #491. Also, not changing the Deployment strategy works better with odh-operator.
**Which issue(s) this PR fixes**
Fixes https://issues.redhat.com/browse/RHOAIENG-18977 …
=> Use leader election for better compatibility with in-place upgrades

config/rbac/role.yaml, pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/openshift_route_reconciler.go, pkg/controller/v1alpha1/inferencegraph/suite_test.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, test/crds/route.openshift.io_routes.yaml
InferenceGraphs doesn't have any ingress reconciler. Despite that, in ODH we need a mechanism to expose InferenceGraphs. This implements exposing InferenceGraphs on OpenShift using Routes.
Fixes https://issues.redhat.com/browse/RHOAIENG-17831
* Create InferenceGraph in Raw mode. Then, check that a route is created and accessible.
* Delete the created Route. Check that the controller restores it.
* Delete the InferenceGraph. Check that the Route is deleted.
**Checklist**:
- [ x Has code been …
=> Implement OpenShift Route creation for InferenceGraphs

docs/odh/networking-visibility.md, docs/odh/oci-model-storage.md
This adds documentations on how to configure as public or private InferenceServices and InferenceGraphs. References from the OCI guide (modelcars) are fixed.
**Which issue(s) this PR fixes** :
Fixes https://issues.redhat.com/browse/RHOAIENG-16311
=> Add docs for networking visibility

test/scripts/openshift-ci/run-e2e-tests.sh, test/scripts/openshift-ci/setup-e2e-tests.sh
Accidentally left out the sed command from https://github.com/opendatahub-io/kserve/pull/477 
Added shell options to the scripts so they would correctly report errors in the CI
=> Fix typo in sed command + Add shell options to scripts

config/overlays/test/kustomization.yaml, test/scripts/openshift-ci/run-e2e-tests.sh, test/scripts/openshift-ci/setup-e2e-tests.sh
What this PR does / why we need it:
Related to [RHOAIENG-14604](https://issues.redhat.com/browse/RHOAIENG-14604)
Cherry picks https://github.com/opendatahub-io/kserve/pull/445, https://github.com/opendatahub-io/kserve/pull/477 and https://github.com/opendatahub-io/kserve/pull/493 
=> [Cherry-pick] Split the e2e test cluster setup into a new script

config/overlays/odh/inferenceservice-config-patch.yaml, pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/components/explainer.go, pkg/controller/v1beta1/inferenceservice/components/predictor.go, pkg/controller/v1beta1/inferenceservice/components/transformer.go, pkg/controller/v1beta1/inferenceservice/controller.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go, pkg/controller/v1beta1/inferenceservice/utils/utils.go
Fixes : [RHOAIENG-20326](https://issues.redhat.com/browse/RHOAIENG-20326) 
- Changes the use of `security.opendatahub.io/enable-auth` from an label to an annotation to match with other uses of the same string 
- Test with https://github.com/opendatahub-io/odh-model-controller/pull/382 
- create raw isvcs with auth enabled using the annotation and verify isvc works as expected (in both cases where route is exposed and where it is not) 
**Checklist**:
- `/rerun-workflow <workflow name>` - …
=> Use annotation instead of label to enable auth for RawDeployment

pkg/apis/serving/v1beta1/configmap.go, pkg/apis/serving/v1beta1/configmap_test.go
This fixes a regression, because in ODH the Services had been headless for Raw deployment mode (see #288). Such default changed to headed services when the feasibility to configure the behavior was introduced, but despite the upstream project has always been using headed services, in ODH this  breaks backwards compatibility.
Thus, this restores the ODH default of using headless services for Raw deployment. Users can still use the inferenceservice-config ConfigMap to switch to headed Services.
https://issues.redhat.com/browse/RHOAIENG-20543
=> Use Headless Services by default

config/rbac/role.yaml, pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/openshift_route_reconciler.go, pkg/webhook/validation/inferenceservice/inferenceservice_webhook_test.go
This adds the possibility to use the `networking.kserve.io/visibility=cluster-local` label to configure an InferenceGraph in Raw mode as private (not exposed).
https://issues.redhat.com/browse/RHOAIENG-20324
- It will be done in the cherry-pick to `master` branch.
* Create InferenceGraph in Raw …
=> Ability to configure Raw InferenceGraphs as private

charts/kserve-resources/templates/clusterrole.yaml, cmd/router/main.go, config/rbac/role.yaml, pkg/constants/constants.go, pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/raw_ig.go, pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
Authorization is implemented by using the TokenReview and the SubjectAccessReview Kubernetes APIs. A Middleware function is setup when some arguments are specified that trigger plugging-in the middleware func.
Some additional reconciliation is added toInferenceGraph controller to:
* Switch to a different ServiceAccount so that privileges for using the cluster APIs are granted.
* Creating the needed ServiceAccount for the auth-protected InferenceGraph to run.
* Managing a ClusterRoleBinding to give the required privileges for auth verification.
Fixes …
=> Implement authorization for Raw InferenceGraphs

pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
This issue was found while using Modelcars feature. For Modelcars, users may prefer using a private container registry to store their models. When using a private registry, it is required to provide a pull secret in the InferenceService so that the cluster can pull the model container.
At any time, and for any reason, users may require to replace/update the pull secret. This operation is done on the InferenceService. It is observed that when replacing the pull secret, the old one won't be removed in the updated deployment.
Fixes #
[RHOAIENG-19717](https://issues.redhat.com//browse/RHOAIENG-19717) …
=> [RHOAIENG-19717] Pod now has correct imagepull secret when updated in raw deployment

pkg/controller/v1alpha1/inferencegraph/controller.go, pkg/controller/v1alpha1/inferencegraph/controller_test.go, pkg/controller/v1alpha1/inferencegraph/openshift_route_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler_test.go
InferenceGraphs do not require oauth-proxy for auth purposes. The auth validation is implemented in kserve-router. This is ensuring that oauth-proxy is not injected to InferenceGraph pods that are deployed in Raw mode.
Also, this is fixing some issues with the management of the related `Service` and `Route`.
Fixes https://issues.redhat.com/browse/RHOAIENG-21300
- Enable auth in an InferenceGraph in Raw mode. Validate that oauth-proxy container is not present.
**Checklist**:
=> Fix oauth-proxy should not be injected to InferenceGraph

test/scripts/openshift-ci/setup-e2e-tests.sh
Fixes # https://issues.redhat.com/browse/RHOAIENG-10406 
- allows specifying odh-model-controller image for e2e test setup such that the same script can be re-used for running kserve e2e tests on odh-model-controller PRs via openshift-ci 
- prereq: fresh cluster
- `ODH_MODEL_CONTROLLER_IMAGE=quay.io/vedantm/odh-model-controller:latest` 
- `./test/scripts/openshift-ci/setup-e2e-tests.sh`
- deployed `odh-model-controller` in namespace `kserve` should use the image `quay.io/vedantm/odh-model-controller:latest`
- `/rerun-all` - rerun …
=> modify e2e setup script to allow specifying odh-model-controller image

config/overlays/odh/inferenceservice-config-patch.yaml, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
Fixes JIRA: https://issues.redhat.com/browse/RHOAIENG-19904 
- override upstream security config for ODH to set `autoMountServiceAccountToken: false` globally
- manually set `autoMountServiceAccountToken: true` while injecting oauth proxy to the deployment for raw isvcs as the token is needed in this case. 
- create raw isvc with auth enabled and ensure inference works. 
**Checklist**:
- `/rerun-workflow <workflow name>` - …
=> disable autoMountServiceAccountToken: true globally 

cmd/router/main.go, pkg/controller/v1alpha1/inferencegraph/raw_ig.go, pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
Fixes https://issues.redhat.com/browse/RHOAIENG-22471 
- add flag to control tls behavior in kserve router 
- verify inferencegraphs can be created and used in Serverless mode. 
- `/rerun-workflow <workflow name>` - rerun …
=> add flag to control tls behavior for kserve router

config/overlays/odh/inferenceservice-config-patch.yaml, hack/verify-doc-links.py, pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/controller_test.go
When an ISVC has changes made to its external route configuration, a new knative revision is created. This behavior is not acceptable to users due to external route management being a different layer than model serving. The expected behavior is that any change enabling/disabling some feature that is not related to serving a model should not create a new revision.
This pull request adds the `networking.knative.io/visibility` annotation to the ServiceAnnotationDisallowedList for ISVCs. This annotation is used to enable/disable the external route for an ISVC. Any annotations that are a member of the ServiceAnnotationDisakkiwedList are prevented from being propagated to knative revisions, which prevents the reconciliation loop from being triggered when …
=> Prevent External Route Changes To ISVCs From Creating New Revisions

test/scripts/openshift-ci/run-e2e-tests.sh
Updating image tag to stable for e2e graph tests to work in the CI
```
=> Updated image tag to stable

config/overlays/test/configmap/inferenceservice-openshift-ci-raw.yaml, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go, test/e2e/batcher/test_raw_batcher.py, test/e2e/custom/test_custom_model_grpc.py, test/e2e/explainer/test_art_explainer.py, test/e2e/graph/test_inference_graph.py, test/e2e/logger/test_raw_logger.py, test/e2e/predictor/test_autoscaling.py, test/e2e/predictor/test_raw_deployment.py, test/scripts/openshift-ci/setup-e2e-tests.sh
- fix raw e2e tests to work with ODH 
- restore some midstream rawdeployment code changes that were lost during syncs from upstream 
- disable gatewayapi unit tests as they are flaky right now, and ODH hasn't adopted gateway api yet. 
Fixes # https://issues.redhat.com/browse/RHOAIENG-20368 
tests re-enabled in CI in https://github.com/openshift/release/pull/63837 
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per …
=> raw e2e test fixes 

cmd/router/main.go
There is a bug when setting up the kserve-router HTTP server endpoint handlers. Upstream project is using the default server mux, but when implementing auth we used a non-default handler.
When upstream introduced readiness probes, the code got mixed and the readiness probe endpoint is not taking effect. This commit fixes the configuration of the http server endpoints.
=> Fix kserve-router HTTP handlers configuration

pkg/controller/v1alpha1/inferencegraph/controller.go
A finalizer is being added on the InferenceGraph CRD for proper clean-up. Since the finalizer code is after resolving URLs of the involved InferenceServices, the `patch` operation over the IG resource would reset the in-memory IG struct object leading to a router-pod being created without the right command-line arguments. An immediate subsequent reconcile fixes the args, but a secondary pod is created.
Moving the configuration of the finalizer before resolving the ISVCs URLs fixes the double-pod creation.
N/A
**Checklist**:
- N/A …
=> Fix kserve-controller creating two InferenceGraph pods

dev_tools/README.md, dev_tools/devspace.yaml
Fixes formatting error in the devspace yaml and adds the ability to run with go1.22 instead of go 1.24 by default. 
=> Add optional go1.22 image and profile to utilize it

test/scripts/openshift-ci/build-kserve-images.sh, test/scripts/openshift-ci/run-e2e-tests.sh
Quality of life script for building kserve images when running e2e tests locally.
Fixes #
=> [RHOAIENG-22171] Added option to build and push kserve images.

pkg/controller/v1alpha1/inferencegraph/raw_ig.go, pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
This is an ODH/OpenShift-specific fix. Since the InferenceServices can be protected under TLS, the InferenceGraph workload requires to trust OpenShift Serving certificates. This fixes kserve-contoller to properly configure the IG router workload to trust needed certificates so that connections succeed.
This issue was found while working on https://issues.redhat.com/browse/RHOAIENG-24595.
1. Please confirm that if this PR changes any image versions, then …
=> Fix Raw InferenceGraph not connecting to ISVCs

config/overlays/odh/kustomization.yaml, config/overlays/odh/params-synced.env, config/overlays/odh/params.env
Reverts opendatahub-io/kserve#640
It will be fixed once is in https://github.com/opendatahub-io/opendatahub-operator/pull/1984
=> Revert "RHOAIENG-25750: Split syncable and static params"

pkg/apis/serving/v1beta1/inference_service.go, pkg/apis/serving/v1beta1/inference_service_status.go, pkg/constants/constants.go, pkg/controller/v1beta1/inferenceservice/components/predictor.go, pkg/controller/v1beta1/inferenceservice/controller.go, pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go, pkg/utils/utils.go
Cherry picks https://github.com/kserve/kserve/pull/4337 and https://github.com/kserve/kserve/pull/4455
=> [Cherry pick v0.14] Stop and resume a model by adding a new annotation 

pkg/controller/llmisvc/controller.go, pkg/controller/llmisvc/llminferenceservice_controller_test.go, pkg/controller/llmisvc/workload.go, pkg/controller/llmisvc/workload_prefill.go, pkg/testing/status_matchers.go
> [!IMPORTANT]
> Ideally this PR should go as "rebase" so we have all 3 commits in history
When `.Spec.Worker` is set to `nil` the existing deployment should be
deleted, instead of created or updated as it is right now.
With the single-node spec this leads to errors in the reconcile as
controller tries to create a worker deployment with empty
`.Spec.Template.Spec`.
If `.Spec.Prefill` is `nil` the expected deployment panics on setting
`.Replicas`. `.Spec` part is not needed in this case as empty
`.Spec.Prefill` results in deleting existing deployment.
We are going to write only to status so there's no need to copy.
With overwriting reference, we are losing sthe tatus calculation when we
exit to main reconcile
=> Various reconcile fixes

pkg/controller/llmisvc/controller.go, pkg/openapi/openapi_generated.go
This change emits events based on actual reconcile error that previously could have been missed when attempt to updating status failed. This can help us spot issues earlier.
=> feat: improves status and events handling

pkg/controller/llmisvc/config_merge_test.go, pkg/controller/llmisvc/config_presets_test.go
This PR is a follow-up to #686 that introduces smoke unit to ensures that all presets defined in `./config/llmisvc` are valid templates.
This not only prevents from wrong usage of quotes (see related PR) but also checks if golang templating is correct.
> [!IMPORTANT]
> Only files prefixed with `config-` are validated.
=> test: ensures presets are valid

pkg/controller/llmisvc/config_merge.go, pkg/controller/llmisvc/config_merge_test.go, pkg/controller/llmisvc/controller_test.go, pkg/testing/httproute_matchers.go
This change allows to use arbitrary struct T in the preset templates by using `{{ .Context.T.Field }}`. This way we can inject KServe configurations such as `IngressConfig`. The templates will now fail on missing keys.
> [!IMPORTANT]
> The templates will now fail on missing keys.
> For simplicity struct is added by it's name without package prefix.
> Anonymous structs are not supported
In addition, copy-pasty bug in `HTTPRoute` matcher has been fixed.
=> feat(presets): additional context in templating

cmd/manager/main.go, config/llmisvc/config-llm-router-route.yaml, docs/samples/llmisvc/opt-125m/llm-inference-service-facebook-opt-125m-cpu.yaml, docs/samples/llmisvc/opt-125m/llm-inference-service-pd-facebook-opt-125m-cpu.yaml, pkg/apis/serving/v1alpha1/llm_inference_service_types_func.go, pkg/controller/llmisvc/config_presets_test.go, pkg/controller/llmisvc/controller.go, pkg/controller/llmisvc/fixture_test.go, pkg/controller/llmisvc/router.go, pkg/controller/llmisvc/suite_test.go, pkg/testing/config.go, pkg/testing/types.go
With this change we can inject configuration from the config map.
There is no need for `.reconcileGateway` with the current approach - we either use default one with `.spec.router.gateway: {}` or we link routes to provided parent.
> [!IMPORTANT]
> We cannot template the namespace in the route preset, because the
validation on Namespace type rejects it for obvious reasons. We keep namespace hardcoded for the time being, but it can be changed by the user in the cluster.
```sh
kind create cluster -n "kserve-llm-d"
go install sigs.k8s.io/cloud-provider-kind@latest
cloud-provider-kind> /dev/null 2>&1 &
make deploy-dev-llm -e KO_DOCKER_REPO=<YOUR_REPO>
kubectl apply -n kserve -f - <<EOF
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
name: facebook-opt-125m-single …
```
=> feat(gw): uses default ingress gateway

pkg/controller/llmisvc/config_merge.go, pkg/controller/llmisvc/config_merge_test.go
The additional tests caught a panic for invalid templates, so now the ReplaceVariables doesn't panic and returns the error instead.
=> Fix panic for invalid templates and add additional tests for MergeSpecs and ReplaceVariables

pkg/controller/llmisvc/DEV.md, pkg/controller/llmisvc/controller_test.go, pkg/controller/llmisvc/fixture/gwapi_builders.go, pkg/controller/llmisvc/fixture/required_resources.go, pkg/controller/llmisvc/router.go, pkg/controller/llmisvc/router_discovery.go, pkg/controller/llmisvc/router_discovery_filter.go, pkg/controller/llmisvc/router_discovery_test.go
This change brings URL resolution by looking up HTTPRoute->Gateways relationship.
If the public addresses are found, one is exposed in `.status.url`, besides that all resolved addresses are populated as `.status.addresses` slice.
> [!IMPORTANT]
>
> Local addresses local (i.e. services) will come as next PR
Following the `DEV.md` guide to deploy your LLMInferenceService, and then try:
```shell
curl $(kubectl get llmisvc -n $NS -o=jsonpath='{.items[0].status.addresses[0].url}')/v1/completions  \
-H "Content-Type: application/json" \
-d '{
"model": "facebook/opt-125m",
"prompt": "San Francisco is a"
}' | jq
```
> [!NOTE]
> Actual address in KinD setup is considered local, hence the jsonpath
above.
you should see similar output:
```shell
{
"id": "cmpl-8482188a-d941-4d8a-96f8-c001e0e03624", …
```
=> feat(router): resolves model URLs

config/llmisvc/config-llm-decode-worker-data-parallel.yaml, config/llmisvc/config-llm-prefill-worker-data-parallel.yaml, config/llmisvc/config-llm-worker-data-parallel.yaml, pkg/controller/llmisvc/config_merge.go
There is built-in `or` function for golang templates. We can use this one instead of custom func.
See: https://pkg.go.dev/text/template#hdr-Functions
=> chore(presets): simplifies template defaulting

pkg/controller/llmisvc/config_presets_test.go, pkg/controller/llmisvc/sample.go
Promotes the previously test-only `LLMInferenceService` sample into a basis for applying `LLMInferenceServiceConfig`s templates during upcoming webhook validation.
Split from #723
=> chore: moves sample LLMInferenceService to its own func

config/default/kustomization.yaml
This PR simplifies how `kustomization.yaml` defines patching of webhooks. The old approach was redundant with nearly indentical replacements repeated for each webhook patch.
Multiple replacements has been merged into single select blocks for all webhooks, so you only define the substitution once per resource type or category and include patch file. There's no need for copy-paste anymore.
Split from #723
=> chore(kustomize): consolidates webhook patching

pkg/controller/llmisvc/scheduler.go
This small PR adds suggestions from the review of #729
- changes logging by using additional key-values
- sorts added service ports for deterministic ordering
=> chore: follow-up to #729

config/llmisvc/config-llm-scheduler.yaml
If the scheduler fails, we would rather serve the request than immediately drop it (for now at least, until we have a better HA story)
https://gateway-api-inference-extension.sigs.k8s.io/reference/spec/?h=failopen#extensionfailuremode
=> Configure scheduler to FailOpen and fallback to random loadbalancing

pkg/agent/watcher_test.go
The HTTP/HTTPS downloader tests were flaky, passing offline and failing online by hitting real example.com endpoints - see this [log for example](https://github.com/opendatahub-io/kserve/actions/runs/16350605009/job/46243788101?pr=750#step:5:619).
To eliminate nondeterminism, tests now target the local httptest server which is defined as test fixture. This prevents test environment leak.
=> fix(test): uses local httptest server urls for downloader tests

config/overlays/test/configmap/inferenceservice.yaml
Without this fix we see following when using `kserve-setup.sh` for CI jobs:
```
Error from server (Forbidden): admission webhook "llminferenceserviceconfig.kserve-webhook-server.validator" denied the request: failed to convert InferenceServiceConfigMap to StorageInitializerConfig: Failed to parse resource configuration for "storageInitializer": "quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
```
=> fix(test): adds required storage initializer settings to test configmap

test/scripts/gh-actions/status-check.sh
Enhances status check for CI jobs to dump pod details and events in the system namespace.
This should help in diagnosing setup issues faster, as previously this was only shown when kserve-setup action succeeded.
> [!NOTE]
> As a follow-up (also upstream) we can remove kubectl commands that are
executed as part of "Install KServe" steps.
=> feat(ci): adds status check for system namespace

pkg/controller/llmisvc/config_merge.go, pkg/controller/llmisvc/config_merge_test.go, pkg/controller/llmisvc/controller_int_test.go, pkg/controller/llmisvc/fixture/llmisvc_builders.go
When using LLMInferenceService with only baseRefs, if one of the configs was zeroing `scheduler: {}` or other elements, the well-known presets were not applied, in contrary, they were removed, as baseRefs were applied after defaulting logic. With this change we resolve baseRefs first to check if we need defaulting.
[Example
Gist](https://gist.github.com/bartoszmajsak/86578f89c27f9c9b05819e68b4f8f0fa)
Additionally, defaulting of model name to LLMInferenceService (`llm-inference-service-model-fb-opt-125m-router-managed-workload` - manifested by the gist above) was causing presets to be ignored, leading to failures of the served model, as it was not able to find wrongly named model in e.g. hugging face repo:
```
ERROR 07-24 10:41:07 [config.py:112] Repository Not Found for url: …
```
=> fix(presets): respects baseRefs defaults

test/e2e/graph/test_inference_graph.py
If `GITHUB_SHA` is not defined as environment variable, running pytest yield error:
```
_______________________________________________________________________ ERROR collecting graph/test_inference_graph.py ________________________________________________________________________
graph/test_inference_graph.py:31: in <module>
SUCCESS_ISVC_IMAGE = "kserve/success-200-isvc:" + os.environ.get("GITHUB_SHA")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   TypeError: can only concatenate str (not "NoneType") to str
_______________________________________________________________________ ERROR collecting graph/test_inference_graph.py ________________________________________________________________________
graph/test_inference_graph.py:31: in <module>
SUCCESS_ISVC_IMAGE = …
```
=> fix: defaults GITHUB_SHA for graph images

pkg/utils/storage.go
fix: Set proper permissions for /mnt directory and add environment variable to change huggingface home dir in storage-initializer
Error msg in storage initializer:
~~~
2025-07-26 03:24:35.983 1 kserve INFO [initializer-entrypoint:setup_mnt_permissions():19] Current process UID: 1000930000, GID: 0
2025-07-26 03:24:35.983 1 kserve INFO [initializer-entrypoint:setup_mnt_permissions():36] Successfully verified write permission to /mnt using group permissions
2025-07-26 03:24:35.983 1 kserve INFO [initializer-entrypoint:<module>():61] Initializing, args: src_uri [hf://facebook/opt-125m] dest_path[ [/mnt/models]
2025-07-26 03:24:35.983 1 kserve INFO [storage.py:download():64] Copying contents of hf://facebook/opt-125m to local
Ignored error while writing …
=> fix: add HuggingFace environment variable(HF_HOME) for storage-initializer

pkg/controller/llmisvc/DEV.md
- uses `kubectl` instead of `oc` to make snippets more portable
- adds wait for CRDs
=> docs: minor fixes in DEV.md

pkg/controller/llmisvc/DEV.md
=> docs: removes obsolote note about errors

pkg/controller/llmisvc/webhook/config_validator.go, pkg/controller/llmisvc/webhook/config_validator_int_test.go
Prevents creation of nested configurations by disallowing `.spec.baseRefs`  in `LLMInferenceServiceConfig` resources. 
As we share the `.spec` between both custom resources we need to make sure that BaseRefs are only used in `LLMInferenceService` resources to reference configuration templates. Using them within the configuration templates introduces additional complexity and can introduce circular dependencies.
=> feat: disallows BaseRefs field in LLMInferenceServiceConfig

pkg/controller/llmisvc/DEV.md
This PR updates DEV.md to use official OSSM 3.1 and this pr is tested with 4.19 nightly build ocp.
=> update dev.md to use official OSSM 3.1

config/monitoring/llmisvc/engine_vllm_monitor.yaml
Use targetPort (even if it's deprecated) as the operator is using old libraries.
=> Fix llmisvc PodMonitor portNumber -> targetPort

pkg/controller/llmisvc/config_loader.go, pkg/controller/llmisvc/controller.go
To simplify upstreaming controller bits the whole Config struct and related functions has been moved to its own file.
This will help upstreaming efforts as it keeps the logic isolated and less vulnerable to merge conflicts moving forward.
=> chore: moves config logic to its own file

Makefile
Adds `kubectl wait` to `deploy` and `deploy-dev` Makefile commands to ensure that the `llminferenceserviceconfigs.serving.kserve.io` crd successfully reaches the `established` condition.
**Checklist**:
=> align deploy command logic in makefile

config/llmisvc/config-llm-decode-template.yaml, config/llmisvc/config-llm-decode-worker-data-parallel.yaml, config/llmisvc/config-llm-prefill-template.yaml, config/llmisvc/config-llm-prefill-worker-data-parallel.yaml, config/llmisvc/config-llm-template.yaml, config/llmisvc/config-llm-worker-data-parallel.yaml, pkg/controller/llmisvc/config_presets_test.go, pkg/controller/llmisvc/controller_workload_storage_int_test.go, pkg/controller/llmisvc/workload.go, pkg/controller/llmisvc/workload_multi_node.go, pkg/controller/llmisvc/workload_storage.go
Port the existing storage-related functionality from single-node workloads to support PVC, OCI, Hugging Face, S3 in multi-node setups.
Both leader and worker pods in the LeaderWorkerSet receive model artifact configuration, and also P/D configurations is covered.
The mutation of the `main` container command to specify the model location had to be removed from the code and hard-coded in the templates.  The motivation is because multi-node (LWS based) deployments are using a smarter start-up script which turns the command more complex. This effectively aligns LLMIsvc implementation to how InferenceServices work: the templates consistently use /mnt/models as the location for loading the model.
**Which issue(s) this PR fixes** *(optional, in `fixes …
=> feat(storage): add model storage support for multi-node LLM workloads (LWS)

pkg/controller/llmisvc/router.go
It has been accidentally removed in #808.
=> fix(router): brings back destination rules reconcile

pkg/controller/llmisvc/fixture/envtest.go
10s seems to not be enough for gh actions as of late.
=> chore(ci): bumps default ginkgo timeout to 30s

docs/samples/llmisvc/opt-125m/llm-inference-service-facebook-opt-125m-cpu-no-scheduler.yaml, pkg/controller/llmisvc/config_merge.go, pkg/controller/llmisvc/controller.go, pkg/controller/llmisvc/controller_int_test.go, pkg/controller/llmisvc/fixture/gwapi_builders.go, pkg/controller/llmisvc/router.go, pkg/controller/llmisvc/scheduler.go, pkg/controller/llmisvc/workload.go, pkg/testing/httproute_matchers.go
Allow 
- using "raw vllm" without inference-scheduler `Gateway` -- (HTTPRoute) --> `Service`
- using external provided InferencePool and scheduler
=> Allow using HTTPRoute without scheduler and external InferencePool Ref

pkg/controller/llmisvc/controller_int_test.go
The `BeControlledBy` method is incorrectly spelled as `BeControllerBy` in the `pkg/controller/llmisvc/controller_int_test.go` file preventing Go Builds from completing successfully due to the following error:
```
go fmt ./pkg/... ./cmd/... && cd qpext && go fmt ./...
pkg/controller/llmisvc/workload.go
pkg/openapi/openapi_generated.go
go vet ./pkg/... ./cmd/... && cd qpext && go vet ./...
vet: pkg/controller/llmisvc/controller_int_test.go:308:34: undefined: BeControllerBy
make: *** [Makefile:70: vet] Error 1
```
**Checklist**:
```release-note
None
```
- `/rerun-workflow <workflow name>` - rerun a …
=> fixing bug caused by misspelled BeControlledBy method

pkg/apis/serving/v1alpha1/llm_inference_service_lifecycle.go, pkg/controller/llmisvc/controller_int_test.go, pkg/controller/llmisvc/fixture/gwapi_builders.go, pkg/controller/llmisvc/router.go, pkg/controller/llmisvc/router_discovery.go
[RHOAIENG-28859](https://issues.redhat.com/browse/RHOAIENG-28859)
Populates the status of InferencePools in an LLMInferenceService, aggregating their readiness to reflect the overall routing readiness in the `RouterReady` condition.
**Checklist**:
=> Add InferencePoolsReady as a subcondition to RouterReady

pkg/controller/llmisvc/workload_tls_self_signed_istio.go
When there is no scheduler, the hostname of the DR must be the workload service.
=> Create DestinationRule with service hostname when there is no scheduler

pkg/controller/llmisvc/workload_tls_self_signed_istio.go
Split workload DestinationRule from shadow service destination rule. The workload service DestinationRule will always be created (when router is configured), while the shadow service one will only be present when the shadow service is present (created by Istio).
=> Always create workload DestinationRule when router is enabled

pkg/controller/llmisvc/router.go
In the current LLMInferenceservice route reconciliation flow, if the LLMInferenceservice route contains references, reconciliation will delete the expected route if it exists and exit reconciliatoin: https://github.com/opendatahub-io/kserve/blob/release-v0.15/pkg/controller/llmisvc/router.go#L107
This premature exit prevents the rest of route reconciliation so the updateRoutingStatus method, which adds the URLs and addresses associated with llmisvc's routes to the llmisvc spec, never gets called.
This PR updates the line above to capture the error returned by the `Delete` method and only return if the error is non nil. This allows route reconciliation to continue as expected and for the proper url/address values to be added to the llmisvc spec for …
=> no longer prematurely exiting llmisvc route reconciliation

test/e2e/predictor/test_autoscaling.py
=> modify keda autoscaling e2e test to work with ODH

pkg/controller/llmisvc/workload_multi_node.go, pkg/controller/llmisvc/workload_single_node.go, pkg/controller/llmisvc/workload_storage.go, pkg/credentials/service_account_credentials.go
[RHOAIENG-33677](https://issues.redhat.com/browse/RHOAIENG-33677)
After work was completed to [enable s3/hf credential usage](https://github.com/opendatahub-io/kserve/pull/842) for llmisvc's using the service account attached to the llmisvc template spec, the `kserve-controller-manager` pod is now excessively logging "Failed to find service account" errors:
```
{"level":"error","ts":"2025-09-02T20:24:14Z","logger":"CredentialBuilder","msg":"Failed to find service account","ServiceAccountName":"facebook-opt-125m-single-kserve-mn","Namespace":"llm-test","error":"serviceaccounts \"facebook-opt-125m-single-kserve-mn\" not found","stacktrace":"github.com/kserve/kserve/pkg/credentials.(*CredentialBuilder).CreateSecretVolumeAndEnv\n\t/go/src/github.com/kser …
```
=> Avoid service account errors

.tekton/kserve-agent-push.yaml, .tekton/kserve-controller-push.yaml, .tekton/kserve-router-push.yaml, .tekton/kserve-storage-initializer-push.yaml, config/overlays/odh/params.env
Update Kserve image tags (non llm-d) to `stable-2.x` in params.env and tekton files
=> update kserve image tags to stable-2.x

config/overlays/odh/patches/patch-inferenceservice-config.yaml, pkg/controller/llmisvc/controller_workload_storage_int_test.go, pkg/credentials/hf/hf_secret.go, pkg/credentials/hf/hf_secret_test.go, pkg/utils/storage.go, pkg/webhook/admission/pod/storage_initializer_injector_test.go
[RHOAIENG-33254](https://issues.redhat.com/browse/RHOAIENG-33254)
When downloading models form hugging face storage using the latest version of the Huggingface Hub python library `Out Of Memory (OOM)` errors are consistently encountered for large models. The cause of this issue is the way kubernetes handles memory overhead when using the `xet` package for hf downloads (discussed in this [issue](https://github.com/huggingface/huggingface_hub/issues/3300#issuecomment-3234260268)).
To lower the memory usage, the following configuration will be used:
1. To maximize download speeds for legacy git lfs storage we will enable the use of the `hf_transfer` package: https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables#hfhubenab …
=> configuring hf downloads to lower memory usage

pkg/controller/llmisvc/DEV.md, test/scripts/openshift-ci/infra/deploy.lws.sh
Migrates the LWS (Leader Worker Set) operator installation from RC/dev build to the official Red Hat `stable-v1.0` operator. This update ensures CI testing and local development use the officially supported operator from the `redhat-operators` catalog instead of custom CatalogSources.
Changes include:
- Updated CI setup script (`test/scripts/openshift-ci/infra/deploy.lws.sh`) to use
`redhat-operators` catalog with `stable-v1.0` channel
- Updated dev guide (`pkg/controller/llmisvc/DEV.md`) to remove RC/brew registry configuration
and use official operator installation
- Removed custom CatalogSource dependency
- Added workaround comment for cert-manager version compatibility
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …
=> Switch to official LWS operator (stable-v1.0) for OpenShift
